import Head from "next/head";

import { useContext, useState } from "react";

//
import { Card } from "../components/Card";

//
import { ThemeProvider } from "styled-components";
import * as Style from "../styles/style";
import { lightTheme, darkTheme } from "../styles/themes";


export default function Home() {

  const [theme, setTheme] = useState("light");

  return (
    <>
      <Head>
        <title>Relógio Digital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
        <ThemeProvider theme={theme =="light" ? lightTheme : darkTheme}>
          <Style.Main>
            <Card theme={theme} setTheme={setTheme}/>
          </Style.Main>
        </ThemeProvider>
    
    </>
  );
  
}
